"""photo_id

Revision ID: 5a0a0ed17a57
Revises: 
Create Date: 2020-04-05 14:10:25.486512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0a0ed17a57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'photo_id')
    # ### end Alembic commands ###
