"""добавили признак публикации

Revision ID: 70433c03a975
Revises: 
Create Date: 2020-04-16 17:28:17.714011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70433c03a975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('identifier', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('categories', 'identifier')
    # ### end Alembic commands ###
